package tpl

var (
	DocsDirName   = "docs"
	DocsFilesName = []string{
		"docs.go",
		"swagger.json",
		"swagger.yaml",
	}
	DocsFilesContent = []string{
		DocsDocsGo,
		DocsSwaggerJson,
		DocsSwaggerYaml,
	}
)

var (
	DocsDocsGo = `// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = ` + "`" + `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://tynam.com",
        "contact": {
            "name": "tynam",
            "url": "https://tynam.com",
            "email": "longtian.jia@service.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/v1/test/test": {
            "get": {
                "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关接口"
                ],
                "summary": "获取测试请求数据接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年龄",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mapi.TestRes"
                        }
                    }
                }
            }
        },
        "/admin/v1/test/user/info": {
            "get": {
                "description": "根据用户id，返回用户信息",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取测试用户信息数据接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "入参",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mredis.User"
                        }
                    }
                }
            }
        },
        "/api/v1/test/test": {
            "get": {
                "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关接口"
                ],
                "summary": "获取测试请求数据接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年龄",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mapi.TestRes"
                        }
                    }
                }
            }
        },
        "/api/v1/test/user/info": {
            "get": {
                "description": "根据用户id，返回用户信息",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取测试用户信息数据接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "入参",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mredis.User"
                        }
                    }
                }
            }
        },
        "/app/v1/test/test": {
            "get": {
                "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关接口"
                ],
                "summary": "获取测试请求数据接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年龄",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mapi.TestRes"
                        }
                    }
                }
            }
        },
        "/app/v1/test/user/info": {
            "get": {
                "description": "根据用户id，返回用户信息",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取测试用户信息数据接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "入参",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mredis.User"
                        }
                    }
                }
            }
        },
        "/i/v1/test/test": {
            "get": {
                "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关接口"
                ],
                "summary": "获取测试请求数据接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "年龄",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "content",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mapi.TestRes"
                        }
                    }
                }
            }
        },
        "/i/v1/test/user/info": {
            "get": {
                "description": "根据用户id，返回用户信息",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关接口"
                ],
                "summary": "获取测试用户信息数据接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "入参",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "$ref": "#/definitions/mredis.User"
                        }
                    }
                }
            }
        },
        "/i/v1/tpl/test": {
            "get": {
                "description": "根据接口请求，返回所有传参",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试相关接口"
                ],
                "summary": "获取模板测试数据接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "入参",
                        "name": "param",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出参",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mapi.TestRes": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "入参数据",
                    "type": "object"
                },
                "time": {
                    "description": "服务器当前时间",
                    "type": "string"
                }
            }
        },
        "mredis.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "租户ID",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        }
    }
}` + "`" + `

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8888",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "模板系统",
	Description: "这是一个模板系统，用于提供框架项目相关开发示例",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
`
	DocsSwaggerJson = `{
  "swagger": "2.0",
  "info": {
    "description": "这是一个模板系统，用于提供框架项目相关开发示例",
    "title": "模板系统",
    "termsOfService": "https://tynam.com",
    "contact": {
      "name": "tynam",
      "url": "https://tynam.com",
      "email": "longtian.jia@service.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0"
  },
  "host": "localhost:8888",
  "basePath": "/",
  "paths": {
    "/admin/v1/test/test": {
      "get": {
        "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "测试相关接口"
        ],
        "summary": "获取测试请求数据接口",
        "parameters": [
          {
            "type": "integer",
            "description": "年龄",
            "name": "age",
            "in": "query"
          },
          {
            "type": "string",
            "description": "内容",
            "name": "content",
            "in": "query"
          },
          {
            "type": "string",
            "description": "名称",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mapi.TestRes"
            }
          }
        }
      }
    },
    "/admin/v1/test/user/info": {
      "get": {
        "description": "根据用户id，返回用户信息",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "用户相关接口"
        ],
        "summary": "获取测试用户信息数据接口",
        "parameters": [
          {
            "type": "string",
            "description": "入参",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mredis.User"
            }
          }
        }
      }
    },
    "/api/v1/test/test": {
      "get": {
        "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "测试相关接口"
        ],
        "summary": "获取测试请求数据接口",
        "parameters": [
          {
            "type": "integer",
            "description": "年龄",
            "name": "age",
            "in": "query"
          },
          {
            "type": "string",
            "description": "内容",
            "name": "content",
            "in": "query"
          },
          {
            "type": "string",
            "description": "名称",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mapi.TestRes"
            }
          }
        }
      }
    },
    "/api/v1/test/user/info": {
      "get": {
        "description": "根据用户id，返回用户信息",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "用户相关接口"
        ],
        "summary": "获取测试用户信息数据接口",
        "parameters": [
          {
            "type": "string",
            "description": "入参",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mredis.User"
            }
          }
        }
      }
    },
    "/app/v1/test/test": {
      "get": {
        "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "测试相关接口"
        ],
        "summary": "获取测试请求数据接口",
        "parameters": [
          {
            "type": "integer",
            "description": "年龄",
            "name": "age",
            "in": "query"
          },
          {
            "type": "string",
            "description": "内容",
            "name": "content",
            "in": "query"
          },
          {
            "type": "string",
            "description": "名称",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mapi.TestRes"
            }
          }
        }
      }
    },
    "/app/v1/test/user/info": {
      "get": {
        "description": "根据用户id，返回用户信息",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "用户相关接口"
        ],
        "summary": "获取测试用户信息数据接口",
        "parameters": [
          {
            "type": "string",
            "description": "入参",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mredis.User"
            }
          }
        }
      }
    },
    "/i/v1/test/test": {
      "get": {
        "description": "根据接口请求，不进行操作，直接返回入参和当前时间",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "测试相关接口"
        ],
        "summary": "获取测试请求数据接口",
        "parameters": [
          {
            "type": "integer",
            "description": "年龄",
            "name": "age",
            "in": "query"
          },
          {
            "type": "string",
            "description": "内容",
            "name": "content",
            "in": "query"
          },
          {
            "type": "string",
            "description": "名称",
            "name": "name",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mapi.TestRes"
            }
          }
        }
      }
    },
    "/i/v1/test/user/info": {
      "get": {
        "description": "根据用户id，返回用户信息",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "用户相关接口"
        ],
        "summary": "获取测试用户信息数据接口",
        "parameters": [
          {
            "type": "string",
            "description": "入参",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "$ref": "#/definitions/mredis.User"
            }
          }
        }
      }
    },
    "/i/v1/tpl/test": {
      "get": {
        "description": "根据接口请求，返回所有传参",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "测试相关接口"
        ],
        "summary": "获取模板测试数据接口",
        "parameters": [
          {
            "type": "string",
            "description": "入参",
            "name": "param",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "出参",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "mapi.TestRes": {
      "type": "object",
      "properties": {
        "data": {
          "description": "入参数据",
          "type": "object"
        },
        "time": {
          "description": "服务器当前时间",
          "type": "string"
        }
      }
    },
    "mredis.User": {
      "type": "object",
      "properties": {
        "created_at": {
          "description": "创建时间",
          "type": "string"
        },
        "id": {
          "description": "id",
          "type": "integer"
        },
        "name": {
          "description": "名称",
          "type": "string"
        },
        "tenant_id": {
          "description": "租户ID",
          "type": "integer"
        },
        "updated_at": {
          "description": "更新时间",
          "type": "string"
        }
      }
    }
  }
}`
	DocsSwaggerYaml = `basePath: /
definitions:
  mapi.TestRes:
    properties:
      data:
        description: 入参数据
        type: object
      time:
        description: 服务器当前时间
        type: string
    type: object
  mredis.User:
    properties:
      created_at:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      name:
        description: 名称
        type: string
      tenant_id:
        description: 租户ID
        type: integer
      updated_at:
        description: 更新时间
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: longtian.jia@service.com
    name: tynam
    url: https://tynam.com
  description: 这是一个模板系统，用于提供框架项目相关开发示例
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://tynam.com
  title: 模板系统
  version: "1.0"
paths:
  /admin/v1/test/test:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据接口请求，不进行操作，直接返回入参和当前时间
      parameters:
        - description: 年龄
          in: query
          name: age
          type: integer
        - description: 内容
          in: query
          name: content
          type: string
        - description: 名称
          in: query
          name: name
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mapi.TestRes'
      summary: 获取测试请求数据接口
      tags:
        - 测试相关接口
  /admin/v1/test/user/info:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据用户id，返回用户信息
      parameters:
        - description: 入参
          in: query
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mredis.User'
      summary: 获取测试用户信息数据接口
      tags:
        - 用户相关接口
  /api/v1/test/test:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据接口请求，不进行操作，直接返回入参和当前时间
      parameters:
        - description: 年龄
          in: query
          name: age
          type: integer
        - description: 内容
          in: query
          name: content
          type: string
        - description: 名称
          in: query
          name: name
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mapi.TestRes'
      summary: 获取测试请求数据接口
      tags:
        - 测试相关接口
  /api/v1/test/user/info:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据用户id，返回用户信息
      parameters:
        - description: 入参
          in: query
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mredis.User'
      summary: 获取测试用户信息数据接口
      tags:
        - 用户相关接口
  /app/v1/test/test:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据接口请求，不进行操作，直接返回入参和当前时间
      parameters:
        - description: 年龄
          in: query
          name: age
          type: integer
        - description: 内容
          in: query
          name: content
          type: string
        - description: 名称
          in: query
          name: name
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mapi.TestRes'
      summary: 获取测试请求数据接口
      tags:
        - 测试相关接口
  /app/v1/test/user/info:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据用户id，返回用户信息
      parameters:
        - description: 入参
          in: query
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mredis.User'
      summary: 获取测试用户信息数据接口
      tags:
        - 用户相关接口
  /i/v1/test/test:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据接口请求，不进行操作，直接返回入参和当前时间
      parameters:
        - description: 年龄
          in: query
          name: age
          type: integer
        - description: 内容
          in: query
          name: content
          type: string
        - description: 名称
          in: query
          name: name
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mapi.TestRes'
      summary: 获取测试请求数据接口
      tags:
        - 测试相关接口
  /i/v1/test/user/info:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据用户id，返回用户信息
      parameters:
        - description: 入参
          in: query
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            $ref: '#/definitions/mredis.User'
      summary: 获取测试用户信息数据接口
      tags:
        - 用户相关接口
  /i/v1/tpl/test:
    get:
      consumes:
        - application/json
        - application/x-www-form-urlencoded
      description: 根据接口请求，返回所有传参
      parameters:
        - description: 入参
          in: query
          name: param
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: 出参
          schema:
            type: string
      summary: 获取模板测试数据接口
      tags:
        - 测试相关接口
swagger: "2.0"
`
)
