- "DbNum": 1001
  "DbName": ""
  "Pool":
    "PoolMinCap": 10
    "PoolMaxCap": 40
    "PoolIdleTimeout": 60000
    "PoolLifeTimeout": 60000
  "Write":
    "Address": "ip"
    "Port": 3306
    "User": "root"
    "Password": "root"
  "Reads":
    - "Address": "ip"
      "Port": 3306
      "User": "root"
      "Password": "root"

- "DbNum": 1002
  "DbName": ""
  "Pool":
    "PoolMinCap": 10
    "PoolExCap": 5
    "PoolMaxCap": 40
    "PoolIdleTimeout": 3600
    "PoolWaitCount": 1000
    "PoolWaitTimeout": 30
  "Write":
    "Address": "ip"
    "Port": 3306
    "User": "root"
    "Password": "root"
  "Reads":
    - "Address": "ip"
      "Port": 3306
      "User": "root"
      "Password": "root"
